// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3xyCaZtNx6ZeDcIplEBP3xJouYVU4nME',
    appId: '1:619566489455:web:2783b3f73284a962e0d29a',
    messagingSenderId: '619566489455',
    projectId: 'cram-schools',
    authDomain: 'cram-schools.firebaseapp.com',
    storageBucket: 'cram-schools.appspot.com',
    measurementId: 'G-FQ1YGYMY6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzVPsKLbFBLc1KntWAhtIEynadNnbK7qA',
    appId: '1:619566489455:android:807220dde7a2e1e3e0d29a',
    messagingSenderId: '619566489455',
    projectId: 'cram-schools',
    storageBucket: 'cram-schools.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiDP21fDY772cedsH0tS5_R3YVamJbmCg',
    appId: '1:619566489455:ios:7d8495353f1c0912e0d29a',
    messagingSenderId: '619566489455',
    projectId: 'cram-schools',
    storageBucket: 'cram-schools.appspot.com',
    iosClientId: '619566489455-c51jp657nqa4769vdmoas56uu93q63o4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSchool',
  );
}
